#!/usr/bin/env bash
# configures a new Ubuntu machine with respect to requirements
sudo apt-get update
sudo apt-get -y install nginx
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i ';' /etc/nginx/sites-enabled/default
sudo service nginx restart

