#!/usr/bin/env bash
# Gets and prints a list of currently running processes,
# shows all processes, for all users, including those which might not have a TTY,
# displays a user-oriented format,
# shows process hierarchy

ps axuf
